### ISSUE TITLE
Problem resolving flutter_ai_toolkit

### ISSUE THREAD

**Issue by luis901101** [davidmigloz/flutter_ai_community#7]
When using the following dependency versions:

```yaml
  flutter_ai_toolkit: ^0.7.1
  flutter_ai_providers: ^0.1.0
```

> Because flutter_ai_providers 0.1.0 depends on flutter_ai_toolkit ^0.6.7 and no versions of flutter_ai_providers match >0.1.0 <0.2.0, flutter_ai_providers ^0.1.0 requires flutter_ai_toolkit ^0.6.7.
So, because sample_ai depends on both flutter_ai_toolkit ^0.7.1 and flutter_ai_providers ^0.1.0, version solving failed.

I think this issue could be avoided if `flutter_ai_providers` included the `flutter_ai_toolkit` dependency with a range of versions until ai_toolkit get above version 1.0.0, I mean something like:

```yaml
flutter_ai_toolkit: '>=0.6.7 <1.0.0'
```

and maybe the same for the rest of the dependencies below 1.0.0

```yaml
  anthropic_sdk_dart: '>=^0.2.0 <1.0.0'
  flutter:
    sdk: flutter
  flutter_ai_toolkit: '>=0.6.7 <1.0.0'
  ollama_dart: '>=^0.2.2 <1.0.0'
  openai_dart: '>=^0.4.5 <1.0.0'
```
